name: vital_chain
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:


  flutter:
    sdk: flutter

  # Cupertino Icons for iOS-style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Flutter Launcher Icons package for generating app icons.
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  # Adding assets for the application.
  assets:
    - web/icons/WhatsApp Image 2025-01-26 at 8.44.37 AM.jpeg
    - assets/images/bot_icon.png
    - assets/images/app_icon.png
