// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzLl4jzmnHaFcHqf1qXUEuR1KdvXMCqLE',
    appId: '1:410417891690:web:1ba0811f66504e30507d13',
    messagingSenderId: '410417891690',
    projectId: 'vitalchain-bd352',
    authDomain: 'vitalchain-bd352.firebaseapp.com',
    storageBucket: 'vitalchain-bd352.firebasestorage.app',
    measurementId: 'G-T718RGLBJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGhYKGmdzRWyAQbNHb7znrjEzvzPLBHjc',
    appId: '1:410417891690:android:22a85079ef185d2c507d13',
    messagingSenderId: '410417891690',
    projectId: 'vitalchain-bd352',
    storageBucket: 'vitalchain-bd352.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEo7y2XsOz-RiCfb8E_AXix7_GPSD9mXE',
    appId: '1:410417891690:ios:96e6eb7428550dca507d13',
    messagingSenderId: '410417891690',
    projectId: 'vitalchain-bd352',
    storageBucket: 'vitalchain-bd352.firebasestorage.app',
    iosBundleId: 'com.example.vitalChain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEo7y2XsOz-RiCfb8E_AXix7_GPSD9mXE',
    appId: '1:410417891690:ios:96e6eb7428550dca507d13',
    messagingSenderId: '410417891690',
    projectId: 'vitalchain-bd352',
    storageBucket: 'vitalchain-bd352.firebasestorage.app',
    iosBundleId: 'com.example.vitalChain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzLl4jzmnHaFcHqf1qXUEuR1KdvXMCqLE',
    appId: '1:410417891690:web:78170b1ae7a5273b507d13',
    messagingSenderId: '410417891690',
    projectId: 'vitalchain-bd352',
    authDomain: 'vitalchain-bd352.firebaseapp.com',
    storageBucket: 'vitalchain-bd352.firebasestorage.app',
    measurementId: 'G-R0JJ3PL6HH',
  );
}
